// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'complete_refund_request.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_CompleteRefundRequest _$$_CompleteRefundRequestFromJson(
        Map<String, dynamic> json) =>
    _$_CompleteRefundRequest(
      responseId: json['ResponseID'] as int,
      transactionId: json['TransactionId'] as int,
      invoiceNo: json['InvoiceNo'] as String,
      tokenId: json['TokenID'] as String,
      recordNo: json['RecordNo'] as String,
      dsixReturnCode: json['DSIXReturnCode'] as String,
      statusId: json['StatusID'] as int,
      textResponse: json['TextResponse'] as String,
      acctNo: json['AcctNo'] as String,
      cardType: json['CardType'] as String,
      tranCode: json['TranCode'] as String,
      refNo: json['RefNo'] as String,
      purchase: json['Purchase'] as String,
      authorize: json['Authorize'] as String,
      transactionDatetime: json['TransactionDatetime'] as String?,
      authCode: json['AuthCode'] as String,
      processData: json['ProcessData'] as String,
      responseOrigin: json['ResponseOrigin'] as String,
      userTraceData: json['UserTraceData'] as String,
      captureStatus: json['CaptureStatus'] as String,
      acqRefData: json['AcqRefData'] as String,
      transactionPaymentGuid: json['TransactionPaymentGuid'] as String,
      creditCardName: json['CreditCardName'] as String,
      nameOnCreditCard: json['NameOnCreditCard'] as String,
      creditCardExpiry: json['CreditCardExpiry'] as String,
      amount: (json['Amount'] as num).toDouble(),
      isActive: json['IsActive'] as bool,
      guid: json['Guid'],
      synchStatus: json['SynchStatus'] as bool,
      siteId: json['SiteId'] as int,
      tipAmount: json['TipAmount'] as String,
      masterEntityId: json['MasterEntityId'] as int,
      createdBy: json['CreatedBy'],
      creationDate: json['CreationDate'],
      lastUpdatedBy: json['LastUpdatedBy'],
      lastUpdateDate: json['LastUpdateDate'],
      customerCopy: json['CustomerCopy'],
      merchantCopy: json['MerchantCopy'],
      customerCardProfileId: json['CustomerCardProfileId'],
      status: json['Status'] as String,
      isChanged: json['IsChanged'] as bool,
    );

Map<String, dynamic> _$$_CompleteRefundRequestToJson(
        _$_CompleteRefundRequest instance) =>
    <String, dynamic>{
      'ResponseID': instance.responseId,
      'TransactionId': instance.transactionId,
      'InvoiceNo': instance.invoiceNo,
      'TokenID': instance.tokenId,
      'RecordNo': instance.recordNo,
      'DSIXReturnCode': instance.dsixReturnCode,
      'StatusID': instance.statusId,
      'TextResponse': instance.textResponse,
      'AcctNo': instance.acctNo,
      'CardType': instance.cardType,
      'TranCode': instance.tranCode,
      'RefNo': instance.refNo,
      'Purchase': instance.purchase,
      'Authorize': instance.authorize,
      'TransactionDatetime': instance.transactionDatetime,
      'AuthCode': instance.authCode,
      'ProcessData': instance.processData,
      'ResponseOrigin': instance.responseOrigin,
      'UserTraceData': instance.userTraceData,
      'CaptureStatus': instance.captureStatus,
      'AcqRefData': instance.acqRefData,
      'TransactionPaymentGuid': instance.transactionPaymentGuid,
      'CreditCardName': instance.creditCardName,
      'NameOnCreditCard': instance.nameOnCreditCard,
      'CreditCardExpiry': instance.creditCardExpiry,
      'Amount': instance.amount,
      'IsActive': instance.isActive,
      'Guid': instance.guid,
      'SynchStatus': instance.synchStatus,
      'SiteId': instance.siteId,
      'TipAmount': instance.tipAmount,
      'MasterEntityId': instance.masterEntityId,
      'CreatedBy': instance.createdBy,
      'CreationDate': instance.creationDate,
      'LastUpdatedBy': instance.lastUpdatedBy,
      'LastUpdateDate': instance.lastUpdateDate,
      'CustomerCopy': instance.customerCopy,
      'MerchantCopy': instance.merchantCopy,
      'CustomerCardProfileId': instance.customerCardProfileId,
      'Status': instance.status,
      'IsChanged': instance.isChanged,
    };
