name: semnox_core
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animate_do: ^2.0.0
  flutter:
    sdk: flutter
  nfc:
    path: core_modules/nfc
  barcode_reader:
    path: ../packages/barcode_reader/
  logs_data:
    path: core_modules/logs_data

  semnox_logger:
    path: core_modules/semnox_logger/

  flutter_icons:
    git:
      url: https://github.com/jibiel/flutter-icons.git
      ref: master
  flutter_slidable: ^0.6.0
  flutter_svg: null
  focus_widget: ^1.0.5+2
  responsive_builder: ^0.4.1
  responsive_framework: ^0.2.0 
  flutter_modular: ^5.0.2
  rxdart: ^0.27.1
  flutter_riverpod: ^2.1.1
  google_fonts: ^3.0.1
  easy_localization: ^3.0.0
  dotted_border: ^2.0.0+1
  flutter_styled_toast: ^2.0.0
  flutter_rating_bar: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  network_info_plus: ^1.1.0
  connectivity_plus: ^1.1.0
  network_tools: ^0.0.4
  dio: ^4.0.0
  auto_animated: ^3.0.0
  easy_localization_loader: ^1.0.0
  uuid: ^3.0.4
  bottom_sheet: ^1.0.4
  tap_canvas: ^0.9.3
  flutter_staggered_animations: ^1.0.0
  package_info_plus: ^3.0.2
  universal_platform: ^1.0.0+1
  jwt_decoder: ^2.0.1
  sqflite_migration: ^0.3.0
  dart_ipify: ^1.1.1
  async: ^2.4.1

  #Utils
  intl: ^0.17.0

dev_dependencies:
  build_runner: null
  # flutter_gen_runner: # ^3.1.1
  flutter_test:
    sdk: flutter
  icon_font_generator: ^2.0.0
  hive_generator: ^1.1.0
  flutter_lints: ^1.0.0
  mockito: ^5.0.15
  

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 900 # Optional (default: 80)
  colors:
    enabled: true

  # Optional
  integrations:
    flutter_svg: true
    
dependency_overrides: null
# Required for null-safety
# PR: https://github.com/flutter-studio/flutter-icons/pull/47
# flutter_icons:
# git:
#   url: git://github.com/jibiel/flutter-icons.git
#   ref: master
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/gif/
    - assets/translations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: SemnoxIcons
  #     fonts:
  #       - asset: assets/icons/semnox_icons.ttf
  fonts:
    - family: GothamRounded
      fonts:

        - asset: assets/fonts/GothamRounded-Bold.otf
          weight: 900
        - asset: assets/fonts/GothamRounded-BoldItalic.otf
          weight: 900
          style: italic

        - asset: assets/fonts/GothamRounded-Bold.otf
          weight: 800
        - asset: assets/fonts/GothamRounded-BoldItalic.otf
          weight: 800
          style: italic

        - asset: assets/fonts/GothamRounded-Bold.otf
          weight: 700
        - asset: assets/fonts/GothamRounded-BoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/GothamRounded-Book.otf
          weight: 600
        - asset: assets/fonts/GothamRounded-BookItalic.otf
          weight: 600
          style: italic

        - asset: assets/fonts/GothamRounded-Medium.otf
          weight: 500
        - asset: assets/fonts/GothamRounded-MediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/GothamRounded-Light.otf
          weight: 400
        - asset: assets/fonts/GothamRounded-LightItalic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/GothamRounded-Light.otf
          weight: 300
        - asset: assets/fonts/GothamRounded-LightItalic.otf
          weight: 300
          style: italic

        - asset: assets/fonts/GothamRounded-Light.otf
          weight: 200
        - asset: assets/fonts/GothamRounded-LightItalic.otf
          weight: 200
          style: italic

        - asset: assets/fonts/GothamRounded-Light.otf
          weight: 100
        - asset: assets/fonts/GothamRounded-LightItalic.otf
          weight: 100
          style: italic

   
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages