name: other_function_ui
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_breadcrumb: ^1.0.1
  execution_context:
    path: ../execution_context
  customer_data:
    path: ../customer_data
  customer_ui:
    path: ../customer_ui
  product_menu_ui:
    path: ../product_menu_ui
  notificationbar_ui:
    path: ../notificationbar_ui
  other_function_data:
    path: ../other_function_data
  master_data:
    path: ../master_data
  login_ui:
    path: ../login_ui
  payment_ui:
    path: ../payment_ui
  nfc:
    path: ../nfc
  widgets_library:
    path: ../widgets_library
  product_menu_data:
    path: ../product_menu_data
  themes_library:
    path: ../themes_library
  messages_data:
    path: ../messages_data
  login_data:
    path: ../login_data
  attendance_ui:
    path: ../attendance_ui
  attendance_data:
    path: ../attendance_data
  orders_ui:
    path: ../orders_ui
  orders_data:
    path: ../orders_data
  shift_tracking_data:
    path: ../shift_tracking_data
  shift_tracking:
    path: ../shift_tracking
  logs_data:
    path: ../logs_data
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.7
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
