name: login_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  network_module:
    path: ../network_module
  login_data:
    path: ../login_data
  execution_context:
    path: ../execution_context
  system_user_login_data:
    path: ../system_user_login_data
  master_data:
    path: ../master_data
  messages_data:
    path: ../messages_data
  application_prefs_data:
    path: ../application_prefs_data
  product_menu_data:
    path: ../product_menu_data
  logs_data:
    path: ../logs_data
  widgets_library:
    path: ../widgets_library
  themes_library:
    path: ../themes_library
  orders_ui:
    path: ../orders_ui

  nfc:
    path: ../nfc
  # for n/w io
  dio: ^4.0.6
  # Bloc for state management
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.3
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  flutter_udid: ^2.0.1
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
