// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_payment_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TransactionPaymentDto _$$_TransactionPaymentDtoFromJson(
        Map<String, dynamic> json) =>
    _$_TransactionPaymentDto(
      paymentId: json['PaymentId'] as int,
      approverId: json['ApproverId'] as int,
      transactionId: json['TransactionId'] as int,
      paymentModeId: json['PaymentModeId'] as int,
      amount: (json['Amount'] as num).toDouble(),
      creditCardNumber: json['CreditCardNumber'] as String,
      nameOnCreditCard: json['NameOnCreditCard'] as String,
      creditCardName: json['CreditCardName'] as String,
      creditCardExpiry: json['CreditCardExpiry'] as String,
      creditCardAuthorization: json['CreditCardAuthorization'] as String,
      cardId: json['CardId'] as int,
      ccResponseId: json['CCResponseId'] as int,
      cardEntitlementType: json['CardEntitlementType'] as String,
      cardCreditPlusId: json['CardCreditPlusId'] as int,
      couponSetId: json['CouponSetId'] as int,
      couponNumber: json['CouponNumber'] as String,
      cpConsumptionId: json['CPConsumptionId'] as int,
      reference: json['Reference'],
      guid: json['Guid'] as String,
      synchStatus: json['SynchStatus'] as bool,
      siteId: json['SiteId'] as int,
      memo: json['Memo'] as String?,
      paymentDate: json['PaymentDate'] as String,
      cashDrawerId: json['CashDrawerId'] as int,
      lastUpdateDate: json['LastUpdateDate'] as String,
      creationDate: json['CreationDate'] as String,
      createdBy: json['CreatedBy'] as String,
      lastUpdatedUser: json['LastUpdatedUser'] as String,
      parentPaymentId: json['ParentPaymentId'] as int,
      tenderedAmount: json['TenderedAmount'],
      tipAmount: (json['TipAmount'] as num).toDouble(),
      posMachine: json['PosMachine'] as String,
      masterEntityId: json['MasterEntityId'] as int,
      currencyCode: json['CurrencyCode'],
      currencyRate: json['CurrencyRate'],
      isTaxable: json['IsTaxable'],
      couponValue: json['CouponValue'],
      approvedBy: json['ApprovedBy'],
      subscriptionAuthorizationMode:
          json['SubscriptionAuthorizationMode'] as int,
      customerCardProfileId: json['CustomerCardProfileId'] as String,
      externalSourceReference: json['ExternalSourceReference'] as String,
      attribute1: json['Attribute1'] as String,
      attribute2: json['Attribute2'] as String,
      attribute3: json['Attribute3'] as String,
      attribute4: json['Attribute4'] as String,
      attribute5: json['Attribute5'] as String,
      paymentStatusId: json['PaymentStatusId'] as int,
      paymentStatus: json['PaymentStatus'] as String,
      paymentStatusChangeDate: json['PaymentStatusChangeDate'] as String,
      isKeyedMode: json['IsKeyedMode'],
      paymentModeOtp: json['PaymentModeOTP'] as String,
      paymentTransactionDTOList:
          json['PaymentTransactionDTOList'] as List<dynamic>,
      transactionPaymentDTOList:
          json['TransactionPaymentDTOList'] as List<dynamic>,
      trxLinePaymentMappingDTOList:
          json['TrxLinePaymentMappingDTOList'] as List<dynamic>,
      isChanged: json['IsChanged'] as bool,
      isChangedRecursive: json['IsChangedRecursive'] as bool,
      isSelected: json['isSelected'] as bool? ?? false,
    );

Map<String, dynamic> _$$_TransactionPaymentDtoToJson(
        _$_TransactionPaymentDto instance) =>
    <String, dynamic>{
      'PaymentId': instance.paymentId,
      'ApproverId': instance.approverId,
      'TransactionId': instance.transactionId,
      'PaymentModeId': instance.paymentModeId,
      'Amount': instance.amount,
      'CreditCardNumber': instance.creditCardNumber,
      'NameOnCreditCard': instance.nameOnCreditCard,
      'CreditCardName': instance.creditCardName,
      'CreditCardExpiry': instance.creditCardExpiry,
      'CreditCardAuthorization': instance.creditCardAuthorization,
      'CardId': instance.cardId,
      'CCResponseId': instance.ccResponseId,
      'CardEntitlementType': instance.cardEntitlementType,
      'CardCreditPlusId': instance.cardCreditPlusId,
      'CouponSetId': instance.couponSetId,
      'CouponNumber': instance.couponNumber,
      'CPConsumptionId': instance.cpConsumptionId,
      'Reference': instance.reference,
      'Guid': instance.guid,
      'SynchStatus': instance.synchStatus,
      'SiteId': instance.siteId,
      'Memo': instance.memo,
      'PaymentDate': instance.paymentDate,
      'CashDrawerId': instance.cashDrawerId,
      'LastUpdateDate': instance.lastUpdateDate,
      'CreationDate': instance.creationDate,
      'CreatedBy': instance.createdBy,
      'LastUpdatedUser': instance.lastUpdatedUser,
      'ParentPaymentId': instance.parentPaymentId,
      'TenderedAmount': instance.tenderedAmount,
      'TipAmount': instance.tipAmount,
      'PosMachine': instance.posMachine,
      'MasterEntityId': instance.masterEntityId,
      'CurrencyCode': instance.currencyCode,
      'CurrencyRate': instance.currencyRate,
      'IsTaxable': instance.isTaxable,
      'CouponValue': instance.couponValue,
      'ApprovedBy': instance.approvedBy,
      'SubscriptionAuthorizationMode': instance.subscriptionAuthorizationMode,
      'CustomerCardProfileId': instance.customerCardProfileId,
      'ExternalSourceReference': instance.externalSourceReference,
      'Attribute1': instance.attribute1,
      'Attribute2': instance.attribute2,
      'Attribute3': instance.attribute3,
      'Attribute4': instance.attribute4,
      'Attribute5': instance.attribute5,
      'PaymentStatusId': instance.paymentStatusId,
      'PaymentStatus': instance.paymentStatus,
      'PaymentStatusChangeDate': instance.paymentStatusChangeDate,
      'IsKeyedMode': instance.isKeyedMode,
      'PaymentModeOTP': instance.paymentModeOtp,
      'PaymentTransactionDTOList': instance.paymentTransactionDTOList,
      'TransactionPaymentDTOList': instance.transactionPaymentDTOList,
      'TrxLinePaymentMappingDTOList': instance.trxLinePaymentMappingDTOList,
      'IsChanged': instance.isChanged,
      'IsChangedRecursive': instance.isChangedRecursive,
      'isSelected': instance.isSelected,
    };
