// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_line_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TransactionLineDTO _$$_TransactionLineDTOFromJson(
        Map<String, dynamic> json) =>
    _$_TransactionLineDTO(
      lineDate: json['LineDate'] as String?,
      lineStatus: json['LineStatus'] as String?,
      lineStatusId: json['LineStatusId'] as int,
      lineStatusChangeDate: json['LineStatusChangeDate'],
      courseName: json['CourseName'] as String?,
      seatName: json['SeatName'] as String?,
      processedForLoyalty: json['ProcessedForLoyalty'] as bool,
      isActive: json['IsActive'] as bool,
      lineReversedDate: json['LineReversedDate'],
      lineFulfilledDate: json['LineFulfilledDate'],
      lineBookedDate: json['LineBookedDate'],
      lineOrderedDate: json['LineOrderedDate'],
      externalSourceReference: json['ExternalSourceReference'] as String?,
      systemReference: json['SystemReference'] as String?,
      comboProductId: json['ComboProductId'] as int,
      modifierSetId: json['ModifierSetId'] as int,
      modifierSetDetailId: json['ModifierSetDetailId'] as int,
      isParentModifier: json['IsParentModifier'] as bool,
      isFreeModifier: json['IsFreeModifier'] as bool,
      isNonChargeable: json['IsNonChargeable'] as bool,
      orderTypeId: json['OrderTypeId'] as int,
      isReversed: json['IsReversed'] as bool,
      viewGroupingNumber: json['ViewGroupingNumber'] as int,
      productSegmentId: json['ProductSegmentId'] as int,
      onPrintHold: json['OnPrintHold'] as bool,
      is9999Product: json['Is9999Product'] as bool,
      isCrossSellProduct: json['IsCrossSellProduct'] as bool,
      isUpsellProduct: json['IsUpsellProduct'] as bool,
      seatNumber: json['SeatNumber'] as int?,
      tagNumber: json['TagNumber'] as String?,
      transactionProfileId: json['TransactionProfileId'] as int,
      accountId: json['AccountId'] as int?,
      priceType: json['PriceType'] as String?,
      userOverriddenPrice: json['UserOverriddenPrice'],
      membershipPrice: json['MembershipPrice'],
      comboAllocatedProductPrice: json['ComboAllocatedProductPrice'],
      promotionPrice: json['PromotionPrice'],
      transactionProfilePrice: json['TransactionProfilePrice'],
      userRolePrice: json['UserRolePrice'],
      basePrice: (json['BasePrice'] as num).toDouble(),
      lineNumber: json['LineNumber'] as int,
      transactionLineId: json['TransactionLineId'] as int,
      categoryId: json['CategoryId'] as int,
      transactionId: json['TransactionId'] as int,
      approvedBy: json['ApprovedBy'] as String?,
      additionalLineInformation: json['AdditionalLineInformation'] as String,
      discountIdentifier: json['DiscountIdentifier'] as String,
      discountIndicator: json['DiscountIndicator'] as String?,
      categoryName: json['CategoryName'] as String?,
      productId: json['ProductId'] as int,
      quantity: (json['Quantity'] as num).toDouble(),
      amount: (json['Amount'] as num).toDouble(),
      netAmount: (json['NetAmount'] as num).toDouble(),
      discountedAmountPreTax:
          (json['DiscountedAmountPreTax'] as num).toDouble(),
      accountCredits: (json['AccountCredits'] as num?)?.toDouble(),
      accountCourtesy: (json['AccountCourtesy'] as num?)?.toDouble(),
      taxPercentage: (json['TaxPercentage'] as num).toDouble(),
      taxId: json['TaxId'] as int,
      taxName: json['TaxName'] as String?,
      parentTransactionLineId: json['ParentTransactionLineId'] as int,
      accountTime: (json['AccountTime'] as num?)?.toDouble(),
      accountBonus: (json['AccountBonus'] as num?)?.toDouble(),
      accountTickets: (json['AccountTickets'] as num?)?.toDouble(),
      accountLoyaltyPoints: (json['AccountLoyaltyPoints'] as num?)?.toDouble(),
      remarks: json['Remarks'] as String,
      promotionId: json['PromotionId'] as int,
      receiptPrinted: json['ReceiptPrinted'] as bool,
      kotPrintCount: json['KOTPrintCount'] as int?,
      gamePlayId: json['GamePlayId'] as int,
      kdsSent: json['KDSSent'] as bool,
      cancelledTime: json['CancelledTime'],
      cancelledBy: json['CancelledBy'] as String?,
      isWaiverSignRequired: json['IsWaiverSignRequired'] as bool,
      originalLineId: json['OriginalLineId'] as int,
      guid: json['Guid'] as String?,
      synchStatus: json['SynchStatus'] as bool,
      siteId: json['SiteId'] as int,
      masterEntityId: json['MasterEntityId'] as int,
      membershipId: json['MembershipId'] as int,
      membershipRewardsId: json['MembershipRewardsId'] as int,
      isChanged: json['IsChanged'] as bool,
      isAmountChanged: json['IsAmountChanged'] as bool,
      isNetAmountChanged: json['IsNetAmountChanged'] as bool?,
      isChangedRecursive: json['IsChangedRecursive'] as bool,
      productName: json['ProductName'] as String,
      createdBy: json['CreatedBy'] as String?,
      creationDate: json['CreationDate'] as String,
      lastUpdatedBy: json['LastUpdatedBy'] as String?,
      lastUpdateDate: json['LastUpdateDate'] as String,
      transactionLineDTOList: (json['TransactionLineDTOList'] as List<dynamic>)
          .map((e) => TransactionLineDTO.fromJson(e as Map<String, dynamic>))
          .toList(),
      transactionAccountDTOList:
          (json['TransactionAccountDTOList'] as List<dynamic>?)
              ?.map((e) =>
                  TransactionLineAccountDto.fromJson(e as Map<String, dynamic>))
              .toList(),
      transactionTaxLineDTOList: (json['TransactionTaxLineDTOList']
              as List<dynamic>)
          .map((e) => TransactionTaxLineDTO.fromJson(e as Map<String, dynamic>))
          .toList(),
      transactionLineKDSOrderEntryMappingDTOList:
          (json['TransactionLineKDSOrderEntryMappingDTOList'] as List<dynamic>?)
              ?.map((e) => TransactionLineKDSOrderEntryMappingDTO.fromJson(
                  e as Map<String, dynamic>))
              .toList(),
      cancelCode: json['CancelCode'] as String?,
    );

Map<String, dynamic> _$$_TransactionLineDTOToJson(
        _$_TransactionLineDTO instance) =>
    <String, dynamic>{
      'LineDate': instance.lineDate,
      'LineStatus': instance.lineStatus,
      'LineStatusId': instance.lineStatusId,
      'LineStatusChangeDate': instance.lineStatusChangeDate,
      'CourseName': instance.courseName,
      'SeatName': instance.seatName,
      'ProcessedForLoyalty': instance.processedForLoyalty,
      'IsActive': instance.isActive,
      'LineReversedDate': instance.lineReversedDate,
      'LineFulfilledDate': instance.lineFulfilledDate,
      'LineBookedDate': instance.lineBookedDate,
      'LineOrderedDate': instance.lineOrderedDate,
      'ExternalSourceReference': instance.externalSourceReference,
      'SystemReference': instance.systemReference,
      'ComboProductId': instance.comboProductId,
      'ModifierSetId': instance.modifierSetId,
      'ModifierSetDetailId': instance.modifierSetDetailId,
      'IsParentModifier': instance.isParentModifier,
      'IsFreeModifier': instance.isFreeModifier,
      'IsNonChargeable': instance.isNonChargeable,
      'OrderTypeId': instance.orderTypeId,
      'IsReversed': instance.isReversed,
      'ViewGroupingNumber': instance.viewGroupingNumber,
      'ProductSegmentId': instance.productSegmentId,
      'OnPrintHold': instance.onPrintHold,
      'Is9999Product': instance.is9999Product,
      'IsCrossSellProduct': instance.isCrossSellProduct,
      'IsUpsellProduct': instance.isUpsellProduct,
      'SeatNumber': instance.seatNumber,
      'TagNumber': instance.tagNumber,
      'TransactionProfileId': instance.transactionProfileId,
      'AccountId': instance.accountId,
      'PriceType': instance.priceType,
      'UserOverriddenPrice': instance.userOverriddenPrice,
      'MembershipPrice': instance.membershipPrice,
      'ComboAllocatedProductPrice': instance.comboAllocatedProductPrice,
      'PromotionPrice': instance.promotionPrice,
      'TransactionProfilePrice': instance.transactionProfilePrice,
      'UserRolePrice': instance.userRolePrice,
      'BasePrice': instance.basePrice,
      'LineNumber': instance.lineNumber,
      'TransactionLineId': instance.transactionLineId,
      'CategoryId': instance.categoryId,
      'TransactionId': instance.transactionId,
      'ApprovedBy': instance.approvedBy,
      'AdditionalLineInformation': instance.additionalLineInformation,
      'DiscountIdentifier': instance.discountIdentifier,
      'DiscountIndicator': instance.discountIndicator,
      'CategoryName': instance.categoryName,
      'ProductId': instance.productId,
      'Quantity': instance.quantity,
      'Amount': instance.amount,
      'NetAmount': instance.netAmount,
      'DiscountedAmountPreTax': instance.discountedAmountPreTax,
      'AccountCredits': instance.accountCredits,
      'AccountCourtesy': instance.accountCourtesy,
      'TaxPercentage': instance.taxPercentage,
      'TaxId': instance.taxId,
      'TaxName': instance.taxName,
      'ParentTransactionLineId': instance.parentTransactionLineId,
      'AccountTime': instance.accountTime,
      'AccountBonus': instance.accountBonus,
      'AccountTickets': instance.accountTickets,
      'AccountLoyaltyPoints': instance.accountLoyaltyPoints,
      'Remarks': instance.remarks,
      'PromotionId': instance.promotionId,
      'ReceiptPrinted': instance.receiptPrinted,
      'KOTPrintCount': instance.kotPrintCount,
      'GamePlayId': instance.gamePlayId,
      'KDSSent': instance.kdsSent,
      'CancelledTime': instance.cancelledTime,
      'CancelledBy': instance.cancelledBy,
      'IsWaiverSignRequired': instance.isWaiverSignRequired,
      'OriginalLineId': instance.originalLineId,
      'Guid': instance.guid,
      'SynchStatus': instance.synchStatus,
      'SiteId': instance.siteId,
      'MasterEntityId': instance.masterEntityId,
      'MembershipId': instance.membershipId,
      'MembershipRewardsId': instance.membershipRewardsId,
      'IsChanged': instance.isChanged,
      'IsAmountChanged': instance.isAmountChanged,
      'IsNetAmountChanged': instance.isNetAmountChanged,
      'IsChangedRecursive': instance.isChangedRecursive,
      'ProductName': instance.productName,
      'CreatedBy': instance.createdBy,
      'CreationDate': instance.creationDate,
      'LastUpdatedBy': instance.lastUpdatedBy,
      'LastUpdateDate': instance.lastUpdateDate,
      'TransactionLineDTOList': instance.transactionLineDTOList,
      'TransactionAccountDTOList': instance.transactionAccountDTOList,
      'TransactionTaxLineDTOList': instance.transactionTaxLineDTOList,
      'TransactionLineKDSOrderEntryMappingDTOList':
          instance.transactionLineKDSOrderEntryMappingDTOList,
      'CancelCode': instance.cancelCode,
    };
