name: product_config_ui
description: A new Flutter package project.
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  form_field_validator:
  dropdown_button2:
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  sprintf: ^7.0.0
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.2.0

  transaction_data:
    path: ../transaction_data
  login_ui:
    path: ../login_ui
  transaction_ui:
    path: ../transaction_ui
  execution_context:
    path: ../execution_context
  notificationbar_ui:
    path: ../notificationbar_ui
  master_data:
    path: ../master_data
  product_menu_data:
    path: ../product_menu_data
  nfc:
    path: ../nfc
  customer_data:
    path: ../customer_data
  logs_data:
    path: ../logs_data
  customer_ui:
    path: ../customer_ui
  widgets_library:
    path: ../widgets_library
  messages_data:
    path: ../messages_data
  themes_library:
    path: ../themes_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  freezed:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

