// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_clocked_in_users_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_GetClockedInUsersData _$$_GetClockedInUsersDataFromJson(
        Map<String, dynamic> json) =>
    _$_GetClockedInUsersData(
      userId: json['UserId'] as int,
      userName: json['UserName'] as String,
      loginId: json['LoginId'] as String,
      roleId: json['RoleId'] as int,
      cardNumber: json['CardNumber'] as String,
      lastLoginTime: json['LastLoginTime'] as String,
      logoutTime: json['LogoutTime'] as String,
      overrideFingerPrint: json['OverrideFingerPrint'] as String,
      passwordHash: json['PasswordHash'],
      passwordSalt: json['PasswordSalt'] as String,
      password: json['Password'] as String,
      masterEntityId: json['MasterEntityId'] as int,
      posTypeId: json['PosTypeId'] as int,
      departmentId: json['DepartmentId'] as int,
      departmentName: json['DepartmentName'] as String,
      empStartDate: DateTime.parse(json['EmpStartDate'] as String),
      empEndDate: DateTime.parse(json['EmpEndDate'] as String),
      empEndReason: json['EmpEndReason'] as String,
      managerId: json['ManagerId'] as int,
      empLastName: json['EmpLastName'] as String,
      empNumber: json['EmpNumber'] as String,
      companyAdministrator: json['CompanyAdministrator'] as String,
      fingerNumber: json['FingerNumber'] as int,
      userStatus: json['UserStatus'] as String,
      passwordChangeDate: json['PasswordChangeDate'] as String,
      invalidAccessAttempts: json['InvalidAccessAttempts'] as int,
      lockedOutTime: json['LockedOutTime'] as String,
      passwordChangeOnNextLogin: json['PasswordChangeOnNextLogin'] as bool,
      email: json['Email'] as String,
      isActive: json['IsActive'] as bool,
      createdBy: json['CreatedBy'] as String,
      creationDate: json['CreationDate'] as String,
      lastUpdatedBy: json['LastUpdatedBy'] as String,
      lastUpdatedDate: json['LastUpdatedDate'] as String,
      guid: json['Guid'] as String,
      siteId: json['SiteId'] as int,
      synchStatus: json['SynchStatus'] as bool,
      dateOfBirth: json['DateOfBirth'] as String?,
      phoneNumber: json['PhoneNumber'] as String,
      shiftConfigurationId: json['ShiftConfigurationId'] as int,
      userIdentificationTagsDtoList:
          json['UserIdentificationTagsDTOList'] as List<dynamic>,
      userPasswordHistoryDtoList:
          json['UserPasswordHistoryDTOList'] as List<dynamic>,
      isChangedRecursive: json['IsChangedRecursive'] as bool,
      isChanged: json['IsChanged'] as bool,
      dataAccessRuleDto: DataAccessRuleDto.fromJson(
          json['DataAccessRuleDTO'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$_GetClockedInUsersDataToJson(
        _$_GetClockedInUsersData instance) =>
    <String, dynamic>{
      'UserId': instance.userId,
      'UserName': instance.userName,
      'LoginId': instance.loginId,
      'RoleId': instance.roleId,
      'CardNumber': instance.cardNumber,
      'LastLoginTime': instance.lastLoginTime,
      'LogoutTime': instance.logoutTime,
      'OverrideFingerPrint': instance.overrideFingerPrint,
      'PasswordHash': instance.passwordHash,
      'PasswordSalt': instance.passwordSalt,
      'Password': instance.password,
      'MasterEntityId': instance.masterEntityId,
      'PosTypeId': instance.posTypeId,
      'DepartmentId': instance.departmentId,
      'DepartmentName': instance.departmentName,
      'EmpStartDate': instance.empStartDate.toIso8601String(),
      'EmpEndDate': instance.empEndDate.toIso8601String(),
      'EmpEndReason': instance.empEndReason,
      'ManagerId': instance.managerId,
      'EmpLastName': instance.empLastName,
      'EmpNumber': instance.empNumber,
      'CompanyAdministrator': instance.companyAdministrator,
      'FingerNumber': instance.fingerNumber,
      'UserStatus': instance.userStatus,
      'PasswordChangeDate': instance.passwordChangeDate,
      'InvalidAccessAttempts': instance.invalidAccessAttempts,
      'LockedOutTime': instance.lockedOutTime,
      'PasswordChangeOnNextLogin': instance.passwordChangeOnNextLogin,
      'Email': instance.email,
      'IsActive': instance.isActive,
      'CreatedBy': instance.createdBy,
      'CreationDate': instance.creationDate,
      'LastUpdatedBy': instance.lastUpdatedBy,
      'LastUpdatedDate': instance.lastUpdatedDate,
      'Guid': instance.guid,
      'SiteId': instance.siteId,
      'SynchStatus': instance.synchStatus,
      'DateOfBirth': instance.dateOfBirth,
      'PhoneNumber': instance.phoneNumber,
      'ShiftConfigurationId': instance.shiftConfigurationId,
      'UserIdentificationTagsDTOList': instance.userIdentificationTagsDtoList,
      'UserPasswordHistoryDTOList': instance.userPasswordHistoryDtoList,
      'IsChangedRecursive': instance.isChangedRecursive,
      'IsChanged': instance.isChanged,
      'DataAccessRuleDTO': instance.dataAccessRuleDto,
    };
