// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'profile_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ProfileDTO _$$_ProfileDTOFromJson(Map<String, dynamic> json) =>
    _$_ProfileDTO(
      id: json['Id'] as int,
      profileTypeId: json['ProfileTypeId'] as int,
      profileType: json['ProfileType'] as int,
      title: json['Title'] as String?,
      firstName: json['FirstName'] as String?,
      nickName: json['NickName'] as String?,
      middleName: json['MiddleName'] as String?,
      lastName: json['LastName'] as String?,
      notes: json['Notes'] as String?,
      dateOfBirth: json['DateOfBirth'] as String?,
      gender: json['Gender'] as String?,
      anniversary: json['Anniversary'] as String?,
      photoURL: json['PhotoURL'] as String?,
      rightHanded: json['RightHanded'] as bool,
      teamUser: json['TeamUser'] as bool,
      uniqueIdentifier: json['UniqueIdentifier'] as String?,
      idProofFileURL: json['IdProofFileURL'] as String?,
      taxCode: json['TaxCode'] as String?,
      designation: json['Designation'] as String?,
      company: json['Company'] as String?,
      userName: json['UserName'] as String?,
      password: json['Password'] as String?,
      lastLoginTime: json['LastLoginTime'] as String?,
      contactDTOList: (json['ContactDTOList'] as List<dynamic>?)
          ?.map((e) => ContactDTO.fromJson(e as Map<String, dynamic>))
          .toList(),
      addressDTOList: (json['AddressDTOList'] as List<dynamic>?)
          ?.map((e) => AddressDTO.fromJson(e as Map<String, dynamic>))
          .toList(),
      profileContentHistoryDTOList: json['ProfileContentHistoryDTOList'],
      optInPromotions: json['OptInPromotions'] as bool,
      optInPromotionsMode: json['OptInPromotionsMode'] as String?,
      optInLastUpdatedDate: json['OptInLastUpdatedDate'] as String?,
      policyTermsAccepted: json['PolicyTermsAccepted'] as bool,
      isActive: json['IsActive'] as bool,
      createdBy: json['CreatedBy'] as String?,
      creationDate: json['CreationDate'] as String?,
      lastUpdatedBy: json['LastUpdatedBy'] as String?,
      lastUpdateDate: json['LastUpdateDate'] as String?,
      siteId: json['SiteId'] as int,
      masterEntityId: json['MasterEntityId'] as int,
      synchStatus: json['SynchStatus'] as bool,
      guid: json['Guid'] as String?,
      externalSystemReference: json['ExternalSystemReference'] as String?,
      optOutWhatsApp: json['OptOutWhatsApp'] as bool,
      userStatus: json['UserStatus'] as String?,
      passwordChangeDate: json['PasswordChangeDate'] as String?,
      invalidAccessAttempts: json['InvalidAccessAttempts'] as int,
      lockedOutTime: json['LockedOutTime'] as String?,
      passwordChangeOnNextLogin: json['PasswordChangeOnNextLogin'] as bool,
      isChanged: json['IsChanged'] as bool,
      isChangedRecursive: json['IsChangedRecursive'] as bool,
      channel: json['Channel'] as String?,
      verified: json['Verified'] as bool?,
    );

Map<String, dynamic> _$$_ProfileDTOToJson(_$_ProfileDTO instance) =>
    <String, dynamic>{
      'Id': instance.id,
      'ProfileTypeId': instance.profileTypeId,
      'ProfileType': instance.profileType,
      'Title': instance.title,
      'FirstName': instance.firstName,
      'NickName': instance.nickName,
      'MiddleName': instance.middleName,
      'LastName': instance.lastName,
      'Notes': instance.notes,
      'DateOfBirth': instance.dateOfBirth,
      'Gender': instance.gender,
      'Anniversary': instance.anniversary,
      'PhotoURL': instance.photoURL,
      'RightHanded': instance.rightHanded,
      'TeamUser': instance.teamUser,
      'UniqueIdentifier': instance.uniqueIdentifier,
      'IdProofFileURL': instance.idProofFileURL,
      'TaxCode': instance.taxCode,
      'Designation': instance.designation,
      'Company': instance.company,
      'UserName': instance.userName,
      'Password': instance.password,
      'LastLoginTime': instance.lastLoginTime,
      'ContactDTOList': instance.contactDTOList,
      'AddressDTOList': instance.addressDTOList,
      'ProfileContentHistoryDTOList': instance.profileContentHistoryDTOList,
      'OptInPromotions': instance.optInPromotions,
      'OptInPromotionsMode': instance.optInPromotionsMode,
      'OptInLastUpdatedDate': instance.optInLastUpdatedDate,
      'PolicyTermsAccepted': instance.policyTermsAccepted,
      'IsActive': instance.isActive,
      'CreatedBy': instance.createdBy,
      'CreationDate': instance.creationDate,
      'LastUpdatedBy': instance.lastUpdatedBy,
      'LastUpdateDate': instance.lastUpdateDate,
      'SiteId': instance.siteId,
      'MasterEntityId': instance.masterEntityId,
      'SynchStatus': instance.synchStatus,
      'Guid': instance.guid,
      'ExternalSystemReference': instance.externalSystemReference,
      'OptOutWhatsApp': instance.optOutWhatsApp,
      'UserStatus': instance.userStatus,
      'PasswordChangeDate': instance.passwordChangeDate,
      'InvalidAccessAttempts': instance.invalidAccessAttempts,
      'LockedOutTime': instance.lockedOutTime,
      'PasswordChangeOnNextLogin': instance.passwordChangeOnNextLogin,
      'IsChanged': instance.isChanged,
      'IsChangedRecursive': instance.isChangedRecursive,
      'Channel': instance.channel,
      'Verified': instance.verified,
    };
